$ANSIBLE_VAULT;1.1;AES256
35626432633363333961666337363932366261623833313261303938333439616436356635323737
6437646366656465643236306435333733333766323866300a653062373037343536613461333936
33653534373032333430313065646361663437373365343335656530363562323836346534613134
3866363732656238610a346162633165363666633136636436623064313036313461393262623065
30623761313835636636303538383539383534336530626133326632643432656564323232313262
65363034366432363238346335343361343666306263623665643235303162613331643837353833
31356635316462393866383033616365343266663964306531323732353466613835643339393539
65326366373230663438643836653037663034663135633564376165323136663962306464663661
3265
