scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["your_vps_ip_here:9090"]

  - job_name: "node"
    static_configs:
      - targets: [host-node-exporter:9100]

rule_files: ["rules/alert-rules.yml"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
